import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useW3Wallet, W3WalletDriver } from "../components/w3wallet"
import Web3 from "web3"
import abi from "../abi/ABI.json"
import getProof from "../utils/getProof"
import { useState } from "react"

export default function Home() {
  const [W3Wallet] = useW3Wallet()
  const { provider, accounts } = W3Wallet
  const account = accounts[0]
  const web3 = new Web3(provider)
  const address = "0xc2CAd2969dCA4902c85b876ffd27bC4f4eE63F23"
  const contract = new web3.eth.Contract(abi, address)

  const [hash, setHash] = useState("")
  const [status, setStatus] = useState("")

  const handleMint = async () => {
    const cost = web3.utils.toWei("0.01", "ether")
    const proof = getProof(account)
    const r = await contract.methods
      .presaleMint(account, 1, proof)
      .send({ from: account, value: cost })
      .on("transactionHash", (hash) => {
        setHash(hash)
        setStatus("pending")
      })
      .on("receipt", (receipt) => {
        console.log(receipt)
        setStatus("success")
      })
      .on("error", (error) => {
        console.log(error)
        setStatus("fail")
      })
      .catch(error => {
        console.log(error)
        setStatus("fail")
      })
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>BS MINT TEST</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {console.log(account)}
      <W3WalletDriver/>
      <button onClick={handleMint}>
        MINT 1
      </button>
      <div>
        txHash: {hash}
      </div>
      <div>
        status: {status}
      </div>
    </div>
  )
}
